-- KHSAA member schools.
--
-- Provenance: supplied by kyboxscore staff (see the hard rules in CLAUDE.md -
-- nothing here is scraped from KHSAA, ArbiterLive or the Riherds archive).
-- Attributed to the 'staff-entry' data source accordingly.
--
-- Only slug and name are asserted. Everything else about a school - mascot,
-- city, county, colors, venue, KHSAA id - is a separate factual claim and is
-- left NULL rather than guessed.
--
-- KNOWN GAP: time_zone defaults to America/New_York for every row, and that is
-- WRONG for western Kentucky. Paducah, Owensboro, Bowling Green and
-- Hopkinsville are Central. Game start times will be an hour off for those
-- schools until county or city data arrives and the zone is corrected. Nothing
-- reads time_zone yet, so this is latent rather than broken.
--
-- Idempotent: re-running updates the name and leaves everything else alone.

INSERT INTO school (slug, name, state, data_source_id)
SELECT v.slug, v.name, 'KY', ds.id
FROM (VALUES
  ('adair-county', 'Adair County High School'),
  ('allen-county-scottsville', 'Allen County-Scottsville High School'),
  ('anderson-county', 'Anderson County High School'),
  ('apollo', 'Apollo High School'),
  ('ashland-blazer', 'Ashland Blazer High School'),
  ('assumption', 'Assumption High School'),
  ('atherton', 'Atherton High School'),
  ('augusta-independent', 'Augusta Independent'),
  ('ballard', 'Ballard High School'),
  ('ballard-memorial', 'Ballard Memorial High School'),
  ('barbourville', 'Barbourville High School'),
  ('bardstown', 'Bardstown High School'),
  ('barren-county', 'Barren County High School'),
  ('bath-county', 'Bath County High School'),
  ('beechwood', 'Beechwood High School'),
  ('belfry', 'Belfry High School'),
  ('bell-county', 'Bell County High School'),
  ('bellevue', 'Bellevue High School'),
  ('berea-community', 'Berea Community High School'),
  ('beth-haven', 'Beth Haven High School'),
  ('bethlehem', 'Bethlehem High School'),
  ('betsy-layne', 'Betsy Layne High School'),
  ('bishop-brossart', 'Bishop Brossart High School'),
  ('boone-county', 'Boone County High School'),
  ('bourbon-county', 'Bourbon County High School'),
  ('bowling-green', 'Bowling Green High School'),
  ('boyd-county', 'Boyd County High School'),
  ('boyle-county', 'Boyle County High School'),
  ('bracken-county', 'Bracken County High School'),
  ('breathitt-county', 'Breathitt County High School'),
  ('breckinridge-county', 'Breckinridge County High School'),
  ('brown', 'Brown High School'),
  ('bryan-station', 'Bryan Station High School'),
  ('buckhorn', 'Buckhorn High School'),
  ('bullitt-central', 'Bullitt Central High School'),
  ('bullitt-east', 'Bullitt East High School'),
  ('burgin', 'Burgin High School'),
  ('butler-county', 'Butler County High School'),
  ('butler', 'Butler High School'),
  ('caldwell-county', 'Caldwell County High School'),
  ('calloway-county', 'Calloway County High School'),
  ('calvary-christian', 'Calvary Christian High School'),
  ('campbell-county', 'Campbell County High School'),
  ('campbellsville', 'Campbellsville High School'),
  ('carlisle-county', 'Carlisle County High School'),
  ('carroll-county', 'Carroll County High School'),
  ('casey-county', 'Casey County High School'),
  ('caverna', 'Caverna High School'),
  ('central-hardin', 'Central Hardin High School'),
  ('central', 'Central High School'),
  ('christian-academy-louisville', 'Christian Academy-Louisville High School'),
  ('christian-county', 'Christian County High School'),
  ('christian-fellowship', 'Christian Fellowship School'),
  ('clay-county', 'Clay County High School'),
  ('clinton-county', 'Clinton County High School'),
  ('cloverport', 'Cloverport High School'),
  ('collins', 'Collins High School'),
  ('community-christian-paducah', 'Community Christian (Paducah) High School'),
  ('community-christian-academy-independence', 'Community Christian Academy (Independence)'),
  ('conner', 'Conner High School'),
  ('cooper', 'Cooper High School'),
  ('corbin', 'Corbin High School'),
  ('cordia', 'Cordia High School'),
  ('cornerstone-christian-academy', 'Cornerstone Christian Academy'),
  ('covington-catholic', 'Covington Catholic High School'),
  ('covington-latin', 'Covington Latin High School'),
  ('crittenden-county', 'Crittenden County High School'),
  ('cumberland-county', 'Cumberland County High School'),
  ('danville-christian-academy', 'Danville Christian Academy'),
  ('danville', 'Danville High School'),
  ('david', 'David School'),
  ('daviess-county', 'Daviess County High School'),
  ('dawson-springs', 'Dawson Springs High School'),
  ('dayton', 'Dayton High School'),
  ('desales', 'Desales High School'),
  ('dixie-heights', 'Dixie Heights High School'),
  ('doss', 'Doss High School'),
  ('dupont-manual', 'Dupont Manual High School'),
  ('east-carter', 'East Carter High School'),
  ('east-jessamine', 'East Jessamine High School'),
  ('east-ridge', 'East Ridge High School'),
  ('eastern', 'Eastern High School'),
  ('edmonson-county', 'Edmonson County High School'),
  ('elizabethtown', 'Elizabethtown High School'),
  ('elliott-county', 'Elliott County High School'),
  ('eminence', 'Eminence High School'),
  ('estill-county', 'Estill County High School'),
  ('evangel-christian', 'Evangel Christian High School'),
  ('fairdale', 'Fairdale High School'),
  ('fairview', 'Fairview High School'),
  ('fern-creek', 'Fern Creek High School'),
  ('fleming-county', 'Fleming County High School'),
  ('floyd-central', 'Floyd Central High School'),
  ('fort-campbell', 'Fort Campbell High School'),
  ('fort-knox', 'Fort Knox High School'),
  ('foundation-christian-academy', 'Foundation Christian Academy'),
  ('francis-parker-school-of-louisville', 'Francis Parker School of Louisville'),
  ('frankfort-christian-academy', 'Frankfort Christian Academy'),
  ('frankfort', 'Frankfort High School'),
  ('franklin-county', 'Franklin County High School'),
  ('franklin-simpson', 'Franklin-Simpson High School'),
  ('frederick-douglass', 'Frederick Douglass High School'),
  ('fulton-city', 'Fulton City High School'),
  ('fulton-county', 'Fulton County High School'),
  ('gallatin-county', 'Gallatin County High School'),
  ('garrard-county', 'Garrard County High School'),
  ('george-rogers-clark', 'George Rogers Clark High School'),
  ('glasgow', 'Glasgow High School'),
  ('grace-james', 'Grace James High School'),
  ('grant-county', 'Grant County High School'),
  ('graves-county', 'Graves County High School'),
  ('grayson-county', 'Grayson County High School'),
  ('great-crossing', 'Great Crossing High School'),
  ('green-county', 'Green County High School'),
  ('greenup-county', 'Greenup County High School'),
  ('greenwood', 'Greenwood High School'),
  ('hancock-county', 'Hancock County High School'),
  ('harlan-county', 'Harlan County High School'),
  ('harlan', 'Harlan High School'),
  ('harrison-county', 'Harrison County High School'),
  ('hart-county', 'Hart County High School'),
  ('hazard', 'Hazard High School'),
  ('henderson-county', 'Henderson County High School'),
  ('henry-clay', 'Henry Clay High School'),
  ('henry-county', 'Henry County High School'),
  ('heritage-christian-academy-hopkinsville', 'Heritage Christian Academy (Hopkinsville)'),
  ('heritage-florence', 'Heritage High School (Florence)'),
  ('hickman-county', 'Hickman County High School'),
  ('highlands', 'Highlands High School'),
  ('highlands-latin', 'Highlands Latin School'),
  ('holmes', 'Holmes High School'),
  ('holy-cross-covington', 'Holy Cross (Covington) High School'),
  ('holy-cross-louisville', 'Holy Cross (Louisville) High School'),
  ('holy-family', 'Holy Family High School'),
  ('hopkins-county-central', 'Hopkins County Central High School'),
  ('hopkinsville', 'Hopkinsville High School'),
  ('iroquois', 'Iroquois High School'),
  ('jackson-city', 'Jackson City High School'),
  ('jackson-county', 'Jackson County High School'),
  ('jeffersontown', 'Jeffersontown High School'),
  ('jenkins', 'Jenkins High School'),
  ('john-hardin', 'John Hardin High School'),
  ('johnson-central', 'Johnson Central High School'),
  ('june-buchanan', 'June Buchanan High School'),
  ('kentucky-country-day', 'Kentucky Country Day High School'),
  ('kentucky-school-for-the-blind', 'Kentucky School f/t Blind High School'),
  ('kentucky-school-for-the-deaf', 'Kentucky School f/t Deaf High School'),
  ('knott-county-central', 'Knott County Central High School'),
  ('knox-central', 'Knox Central High School'),
  ('lafayette', 'Lafayette High School'),
  ('larry-a-ryle', 'Larry A Ryle High School'),
  ('larue-county', 'Larue County High School'),
  ('lawrence-county', 'Lawrence County High School'),
  ('lee-county', 'Lee County High School'),
  ('leslie-county', 'Leslie County High School'),
  ('letcher-county-central', 'Letcher County Central High School'),
  ('lewis-county', 'Lewis County High School'),
  ('lexington-catholic', 'Lexington Catholic High School'),
  ('lexington-christian-academy', 'Lexington Christian Academy'),
  ('lincoln-county', 'Lincoln County High School'),
  ('livingston-central', 'Livingston Central High School'),
  ('lloyd-memorial', 'Lloyd Memorial High School'),
  ('logan-county', 'Logan County High School'),
  ('louisville-collegiate', 'Louisville Collegiate School'),
  ('ludlow', 'Ludlow High School'),
  ('lynn-camp', 'Lynn Camp High School'),
  ('lyon-county', 'Lyon County High School'),
  ('madison-central', 'Madison Central High School'),
  ('madison-southern', 'Madison Southern High School'),
  ('madisonville-north-hopkins', 'Madisonville-North Hopkins High School'),
  ('magoffin-county', 'Magoffin County High School'),
  ('male', 'Male High School'),
  ('marion-county', 'Marion County High School'),
  ('marshall-county', 'Marshall County High School'),
  ('martin-county', 'Martin County High School'),
  ('mason-county', 'Mason County High School'),
  ('mayfield', 'Mayfield High School'),
  ('mccracken-county', 'McCracken County High School'),
  ('mccreary-central', 'McCreary Central High School'),
  ('mclean-county', 'McLean County High School'),
  ('meade-county', 'Meade County High School'),
  ('menifee-county', 'Menifee County High School'),
  ('mercer-county', 'Mercer County High School'),
  ('mercy-academy', 'Mercy Academy'),
  ('metcalfe-county', 'Metcalfe County High School'),
  ('mhg-preparatory-academy', 'MHG Preparatory Academy'),
  ('middlesboro', 'Middlesboro High School'),
  ('model', 'Model High School'),
  ('monroe-county', 'Monroe County High School'),
  ('montgomery-county', 'Montgomery County High School'),
  ('moore', 'Moore High School'),
  ('morgan-county', 'Morgan County High School'),
  ('muhlenberg-county', 'Muhlenberg County High School'),
  ('murray', 'Murray High School'),
  ('nelson-county', 'Nelson County High School'),
  ('newcomer-academy', 'Newcomer Academy'),
  ('newport-central-catholic', 'Newport Central Catholic High School'),
  ('newport', 'Newport High School'),
  ('nicholas-county', 'Nicholas County High School'),
  ('north-bullitt', 'North Bullitt High School'),
  ('north-hardin', 'North Hardin High School'),
  ('north-laurel', 'North Laurel High School'),
  ('north-oldham', 'North Oldham High School'),
  ('notre-dame-academy', 'Notre Dame Academy'),
  ('ohio-county', 'Ohio County High School'),
  ('oldham-county', 'Oldham County High School'),
  ('oneida-baptist-institute', 'Oneida Baptist Institute High School'),
  ('owen-county', 'Owen County High School'),
  ('owensboro-catholic', 'Owensboro Catholic High School'),
  ('owensboro', 'Owensboro High School'),
  ('owsley-county', 'Owsley County High School'),
  ('paducah-tilghman', 'Paducah Tilghman High School'),
  ('paintsville', 'Paintsville High School'),
  ('paris', 'Paris High School'),
  ('paul-laurence-dunbar', 'Paul Laurence Dunbar High School'),
  ('pendleton-county', 'Pendleton County High School'),
  ('perry-county-central', 'Perry County Central High School'),
  ('phelps', 'Phelps High School'),
  ('piarist', 'Piarist High School'),
  ('pike-county-central', 'Pike County Central High School'),
  ('pikeville', 'Pikeville High School'),
  ('pineville', 'Pineville High School'),
  ('pleasure-ridge-park', 'Pleasure Ridge Park High School'),
  ('portland-christian', 'Portland Christian High School'),
  ('powell-county', 'Powell County High School'),
  ('presentation-academy', 'Presentation Academy'),
  ('prestonsburg', 'Prestonsburg High School'),
  ('pulaski-county', 'Pulaski County High School'),
  ('raceland', 'Raceland High School'),
  ('red-bird-christian', 'Red Bird Christian High School'),
  ('riverside-christian', 'Riverside Christian High School'),
  ('robertson-county', 'Robertson County High School'),
  ('rockcastle-county', 'Rockcastle County High School'),
  ('rose-hill-christian', 'Rose Hill Christian School'),
  ('rowan-county', 'Rowan County Senior High School'),
  ('russell-county', 'Russell County High School'),
  ('russell', 'Russell High School'),
  ('russellville', 'Russellville High School'),
  ('sacred-heart-academy', 'Sacred Heart Academy'),
  ('saint-xavier', 'Saint Xavier High School'),
  ('sayre', 'Sayre High School'),
  ('scott-county', 'Scott County High School'),
  ('scott', 'Scott High School'),
  ('seneca', 'Seneca High School'),
  ('shawnee', 'Shawnee High School'),
  ('shelby-county', 'Shelby County High School'),
  ('shelby-valley', 'Shelby Valley High School'),
  ('simon-kenton', 'Simon Kenton High School'),
  ('somerset-christian', 'Somerset Christian School'),
  ('somerset', 'Somerset High School'),
  ('south-laurel', 'South Laurel High School'),
  ('south-oldham', 'South Oldham High School'),
  ('south-warren', 'South Warren High School'),
  ('southern', 'Southern High School'),
  ('southwestern', 'Southwestern High School'),
  ('spencer-county', 'Spencer County High School'),
  ('st-henry-district', 'St. Henry District High School'),
  ('st-mary', 'St. Mary High School'),
  ('st-patrick', 'St. Patrick High School'),
  ('tates-creek', 'Tates Creek High School'),
  ('taylor-county', 'Taylor County High School'),
  ('thomas-nelson', 'Thomas Nelson High School'),
  ('todd-county-central', 'Todd County Central High School'),
  ('trigg-county', 'Trigg County High School'),
  ('trimble-county', 'Trimble County High School'),
  ('trinity-louisville', 'Trinity (Louisville) High School'),
  ('trinity-whitesville', 'Trinity (Whitesville) High School'),
  ('trinity-christian-academy', 'Trinity Christian Academy'),
  ('union-county', 'Union County High School'),
  ('university-heights', 'University Heights High School'),
  ('valley', 'Valley High School'),
  ('villa-madonna-academy', 'Villa Madonna Academy'),
  ('w-e-b-dubois', 'W.E.B. DuBois High School'),
  ('waggener', 'Waggener High School'),
  ('walden', 'Walden High School'),
  ('walton-verona', 'Walton-Verona High School'),
  ('warren-central', 'Warren Central High School'),
  ('warren-east', 'Warren East High School'),
  ('washington-county', 'Washington County High School'),
  ('wayne-county', 'Wayne County High School'),
  ('webster-county', 'Webster County High School'),
  ('west-carter', 'West Carter High School'),
  ('west-jessamine', 'West Jessamine High School'),
  ('western', 'Western High School'),
  ('western-hills', 'Western Hills High School'),
  ('whitefield-academy', 'Whitefield Academy'),
  ('whitley-county', 'Whitley County High School'),
  ('williamsburg', 'Williamsburg High School'),
  ('williamstown', 'Williamstown High School'),
  ('wolfe-county', 'Wolfe County High School'),
  ('woodford-county', 'Woodford County High School')
) AS v(slug, name)
CROSS JOIN data_source ds
WHERE ds.slug = 'staff-entry'
ON CONFLICT (slug) DO UPDATE
  SET name = EXCLUDED.name,
      updated_at = now();
