-- KHSAA member schools.
--
-- Provenance: supplied by kyboxscore staff (see the hard rules in CLAUDE.md -
-- nothing here is scraped from KHSAA, ArbiterLive or the Riherds archive).
-- Attributed to the 'staff-entry' data source accordingly.
--
-- Three columns are asserted: slug, the full legal name, and short_name.
--
-- short_name is the scoreboard label - "John Hardin", not "John Hardin High
-- School". The full name is kept because it is what the school is actually
-- called, because school matching on imports relies on it, and because a
-- record book should hold the real name. Display reads short_name; matching
-- reads name. Parenthetical disambiguators survive into the short name:
-- "Trinity (Louisville)" without them would be two different schools.
--
-- Everything else about a school - mascot, city, county, colors, venue, KHSAA
-- id - is a separate factual claim and is left NULL rather than guessed.
--
-- KNOWN GAP: time_zone defaults to America/New_York for every row, and that is
-- WRONG for western Kentucky. Paducah, Owensboro, Bowling Green and
-- Hopkinsville are Central. Game start times will be an hour off for those
-- schools until county or city data arrives and the zone is corrected.
--
-- Idempotent: re-running updates the names and leaves everything else alone.

INSERT INTO school (slug, name, short_name, state, data_source_id)
SELECT v.slug, v.name, v.short_name, 'KY', ds.id
FROM (VALUES
  ('adair-county', 'Adair County High School', 'Adair County'),
  ('allen-county-scottsville', 'Allen County-Scottsville High School', 'Allen County-Scottsville'),
  ('anderson-county', 'Anderson County High School', 'Anderson County'),
  ('apollo', 'Apollo High School', 'Apollo'),
  ('ashland-blazer', 'Ashland Blazer High School', 'Ashland Blazer'),
  ('assumption', 'Assumption High School', 'Assumption'),
  ('atherton', 'Atherton High School', 'Atherton'),
  ('augusta-independent', 'Augusta Independent', 'Augusta Independent'),
  ('ballard', 'Ballard High School', 'Ballard'),
  ('ballard-memorial', 'Ballard Memorial High School', 'Ballard Memorial'),
  ('barbourville', 'Barbourville High School', 'Barbourville'),
  ('bardstown', 'Bardstown High School', 'Bardstown'),
  ('barren-county', 'Barren County High School', 'Barren County'),
  ('bath-county', 'Bath County High School', 'Bath County'),
  ('beechwood', 'Beechwood High School', 'Beechwood'),
  ('belfry', 'Belfry High School', 'Belfry'),
  ('bell-county', 'Bell County High School', 'Bell County'),
  ('bellevue', 'Bellevue High School', 'Bellevue'),
  ('berea-community', 'Berea Community High School', 'Berea Community'),
  ('beth-haven', 'Beth Haven High School', 'Beth Haven'),
  ('bethlehem', 'Bethlehem High School', 'Bethlehem'),
  ('betsy-layne', 'Betsy Layne High School', 'Betsy Layne'),
  ('bishop-brossart', 'Bishop Brossart High School', 'Bishop Brossart'),
  ('boone-county', 'Boone County High School', 'Boone County'),
  ('bourbon-county', 'Bourbon County High School', 'Bourbon County'),
  ('bowling-green', 'Bowling Green High School', 'Bowling Green'),
  ('boyd-county', 'Boyd County High School', 'Boyd County'),
  ('boyle-county', 'Boyle County High School', 'Boyle County'),
  ('bracken-county', 'Bracken County High School', 'Bracken County'),
  ('breathitt-county', 'Breathitt County High School', 'Breathitt County'),
  ('breckinridge-county', 'Breckinridge County High School', 'Breckinridge County'),
  ('brown', 'Brown High School', 'Brown'),
  ('bryan-station', 'Bryan Station High School', 'Bryan Station'),
  ('buckhorn', 'Buckhorn High School', 'Buckhorn'),
  ('bullitt-central', 'Bullitt Central High School', 'Bullitt Central'),
  ('bullitt-east', 'Bullitt East High School', 'Bullitt East'),
  ('burgin', 'Burgin High School', 'Burgin'),
  ('butler-county', 'Butler County High School', 'Butler County'),
  ('butler', 'Butler High School', 'Butler'),
  ('caldwell-county', 'Caldwell County High School', 'Caldwell County'),
  ('calloway-county', 'Calloway County High School', 'Calloway County'),
  ('calvary-christian', 'Calvary Christian High School', 'Calvary Christian'),
  ('campbell-county', 'Campbell County High School', 'Campbell County'),
  ('campbellsville', 'Campbellsville High School', 'Campbellsville'),
  ('carlisle-county', 'Carlisle County High School', 'Carlisle County'),
  ('carroll-county', 'Carroll County High School', 'Carroll County'),
  ('casey-county', 'Casey County High School', 'Casey County'),
  ('caverna', 'Caverna High School', 'Caverna'),
  ('central-hardin', 'Central Hardin High School', 'Central Hardin'),
  ('central', 'Central High School', 'Central'),
  ('christian-academy-louisville', 'Christian Academy-Louisville High School', 'Christian Academy-Louisville'),
  ('christian-county', 'Christian County High School', 'Christian County'),
  ('christian-fellowship', 'Christian Fellowship School', 'Christian Fellowship'),
  ('clay-county', 'Clay County High School', 'Clay County'),
  ('clinton-county', 'Clinton County High School', 'Clinton County'),
  ('cloverport', 'Cloverport High School', 'Cloverport'),
  ('collins', 'Collins High School', 'Collins'),
  ('community-christian-paducah', 'Community Christian (Paducah) High School', 'Community Christian (Paducah)'),
  ('community-christian-academy-independence', 'Community Christian Academy (Independence)', 'Community Christian Academy (Independence)'),
  ('conner', 'Conner High School', 'Conner'),
  ('cooper', 'Cooper High School', 'Cooper'),
  ('corbin', 'Corbin High School', 'Corbin'),
  ('cordia', 'Cordia High School', 'Cordia'),
  ('cornerstone-christian-academy', 'Cornerstone Christian Academy', 'Cornerstone Christian Academy'),
  ('covington-catholic', 'Covington Catholic High School', 'Covington Catholic'),
  ('covington-latin', 'Covington Latin High School', 'Covington Latin'),
  ('crittenden-county', 'Crittenden County High School', 'Crittenden County'),
  ('cumberland-county', 'Cumberland County High School', 'Cumberland County'),
  ('danville-christian-academy', 'Danville Christian Academy', 'Danville Christian Academy'),
  ('danville', 'Danville High School', 'Danville'),
  ('david', 'David School', 'David'),
  ('daviess-county', 'Daviess County High School', 'Daviess County'),
  ('dawson-springs', 'Dawson Springs High School', 'Dawson Springs'),
  ('dayton', 'Dayton High School', 'Dayton'),
  ('desales', 'Desales High School', 'Desales'),
  ('dixie-heights', 'Dixie Heights High School', 'Dixie Heights'),
  ('doss', 'Doss High School', 'Doss'),
  ('dupont-manual', 'Dupont Manual High School', 'Dupont Manual'),
  ('east-carter', 'East Carter High School', 'East Carter'),
  ('east-jessamine', 'East Jessamine High School', 'East Jessamine'),
  ('east-ridge', 'East Ridge High School', 'East Ridge'),
  ('eastern', 'Eastern High School', 'Eastern'),
  ('edmonson-county', 'Edmonson County High School', 'Edmonson County'),
  ('elizabethtown', 'Elizabethtown High School', 'Elizabethtown'),
  ('elliott-county', 'Elliott County High School', 'Elliott County'),
  ('eminence', 'Eminence High School', 'Eminence'),
  ('estill-county', 'Estill County High School', 'Estill County'),
  ('evangel-christian', 'Evangel Christian High School', 'Evangel Christian'),
  ('fairdale', 'Fairdale High School', 'Fairdale'),
  ('fairview', 'Fairview High School', 'Fairview'),
  ('fern-creek', 'Fern Creek High School', 'Fern Creek'),
  ('fleming-county', 'Fleming County High School', 'Fleming County'),
  ('floyd-central', 'Floyd Central High School', 'Floyd Central'),
  ('fort-campbell', 'Fort Campbell High School', 'Fort Campbell'),
  ('fort-knox', 'Fort Knox High School', 'Fort Knox'),
  ('foundation-christian-academy', 'Foundation Christian Academy', 'Foundation Christian Academy'),
  ('francis-parker-school-of-louisville', 'Francis Parker School of Louisville', 'Francis Parker School of Louisville'),
  ('frankfort-christian-academy', 'Frankfort Christian Academy', 'Frankfort Christian Academy'),
  ('frankfort', 'Frankfort High School', 'Frankfort'),
  ('franklin-county', 'Franklin County High School', 'Franklin County'),
  ('franklin-simpson', 'Franklin-Simpson High School', 'Franklin-Simpson'),
  ('frederick-douglass', 'Frederick Douglass High School', 'Frederick Douglass'),
  ('fulton-city', 'Fulton City High School', 'Fulton City'),
  ('fulton-county', 'Fulton County High School', 'Fulton County'),
  ('gallatin-county', 'Gallatin County High School', 'Gallatin County'),
  ('garrard-county', 'Garrard County High School', 'Garrard County'),
  ('george-rogers-clark', 'George Rogers Clark High School', 'George Rogers Clark'),
  ('glasgow', 'Glasgow High School', 'Glasgow'),
  ('grace-james', 'Grace James High School', 'Grace James'),
  ('grant-county', 'Grant County High School', 'Grant County'),
  ('graves-county', 'Graves County High School', 'Graves County'),
  ('grayson-county', 'Grayson County High School', 'Grayson County'),
  ('great-crossing', 'Great Crossing High School', 'Great Crossing'),
  ('green-county', 'Green County High School', 'Green County'),
  ('greenup-county', 'Greenup County High School', 'Greenup County'),
  ('greenwood', 'Greenwood High School', 'Greenwood'),
  ('hancock-county', 'Hancock County High School', 'Hancock County'),
  ('harlan-county', 'Harlan County High School', 'Harlan County'),
  ('harlan', 'Harlan High School', 'Harlan'),
  ('harrison-county', 'Harrison County High School', 'Harrison County'),
  ('hart-county', 'Hart County High School', 'Hart County'),
  ('hazard', 'Hazard High School', 'Hazard'),
  ('henderson-county', 'Henderson County High School', 'Henderson County'),
  ('henry-clay', 'Henry Clay High School', 'Henry Clay'),
  ('henry-county', 'Henry County High School', 'Henry County'),
  ('heritage-christian-academy-hopkinsville', 'Heritage Christian Academy (Hopkinsville)', 'Heritage Christian Academy (Hopkinsville)'),
  ('heritage-florence', 'Heritage High School (Florence)', 'Heritage (Florence)'),
  ('hickman-county', 'Hickman County High School', 'Hickman County'),
  ('highlands', 'Highlands High School', 'Highlands'),
  ('highlands-latin', 'Highlands Latin School', 'Highlands Latin'),
  ('holmes', 'Holmes High School', 'Holmes'),
  ('holy-cross-covington', 'Holy Cross (Covington) High School', 'Holy Cross (Covington)'),
  ('holy-cross-louisville', 'Holy Cross (Louisville) High School', 'Holy Cross (Louisville)'),
  ('holy-family', 'Holy Family High School', 'Holy Family'),
  ('hopkins-county-central', 'Hopkins County Central High School', 'Hopkins County Central'),
  ('hopkinsville', 'Hopkinsville High School', 'Hopkinsville'),
  ('iroquois', 'Iroquois High School', 'Iroquois'),
  ('jackson-city', 'Jackson City High School', 'Jackson City'),
  ('jackson-county', 'Jackson County High School', 'Jackson County'),
  ('jeffersontown', 'Jeffersontown High School', 'Jeffersontown'),
  ('jenkins', 'Jenkins High School', 'Jenkins'),
  ('john-hardin', 'John Hardin High School', 'John Hardin'),
  ('johnson-central', 'Johnson Central High School', 'Johnson Central'),
  ('june-buchanan', 'June Buchanan High School', 'June Buchanan'),
  ('kentucky-country-day', 'Kentucky Country Day High School', 'Kentucky Country Day'),
  ('kentucky-school-for-the-blind', 'Kentucky School f/t Blind High School', 'Kentucky School f/t Blind'),
  ('kentucky-school-for-the-deaf', 'Kentucky School f/t Deaf High School', 'Kentucky School f/t Deaf'),
  ('knott-county-central', 'Knott County Central High School', 'Knott County Central'),
  ('knox-central', 'Knox Central High School', 'Knox Central'),
  ('lafayette', 'Lafayette High School', 'Lafayette'),
  ('larry-a-ryle', 'Larry A Ryle High School', 'Larry A Ryle'),
  ('larue-county', 'Larue County High School', 'Larue County'),
  ('lawrence-county', 'Lawrence County High School', 'Lawrence County'),
  ('lee-county', 'Lee County High School', 'Lee County'),
  ('leslie-county', 'Leslie County High School', 'Leslie County'),
  ('letcher-county-central', 'Letcher County Central High School', 'Letcher County Central'),
  ('lewis-county', 'Lewis County High School', 'Lewis County'),
  ('lexington-catholic', 'Lexington Catholic High School', 'Lexington Catholic'),
  ('lexington-christian-academy', 'Lexington Christian Academy', 'Lexington Christian Academy'),
  ('lincoln-county', 'Lincoln County High School', 'Lincoln County'),
  ('livingston-central', 'Livingston Central High School', 'Livingston Central'),
  ('lloyd-memorial', 'Lloyd Memorial High School', 'Lloyd Memorial'),
  ('logan-county', 'Logan County High School', 'Logan County'),
  ('louisville-collegiate', 'Louisville Collegiate School', 'Louisville Collegiate'),
  ('ludlow', 'Ludlow High School', 'Ludlow'),
  ('lynn-camp', 'Lynn Camp High School', 'Lynn Camp'),
  ('lyon-county', 'Lyon County High School', 'Lyon County'),
  ('madison-central', 'Madison Central High School', 'Madison Central'),
  ('madison-southern', 'Madison Southern High School', 'Madison Southern'),
  ('madisonville-north-hopkins', 'Madisonville-North Hopkins High School', 'Madisonville-North Hopkins'),
  ('magoffin-county', 'Magoffin County High School', 'Magoffin County'),
  ('male', 'Male High School', 'Male'),
  ('marion-county', 'Marion County High School', 'Marion County'),
  ('marshall-county', 'Marshall County High School', 'Marshall County'),
  ('martin-county', 'Martin County High School', 'Martin County'),
  ('mason-county', 'Mason County High School', 'Mason County'),
  ('mayfield', 'Mayfield High School', 'Mayfield'),
  ('mccracken-county', 'McCracken County High School', 'McCracken County'),
  ('mccreary-central', 'McCreary Central High School', 'McCreary Central'),
  ('mclean-county', 'McLean County High School', 'McLean County'),
  ('meade-county', 'Meade County High School', 'Meade County'),
  ('menifee-county', 'Menifee County High School', 'Menifee County'),
  ('mercer-county', 'Mercer County High School', 'Mercer County'),
  ('mercy-academy', 'Mercy Academy', 'Mercy Academy'),
  ('metcalfe-county', 'Metcalfe County High School', 'Metcalfe County'),
  ('mhg-preparatory-academy', 'MHG Preparatory Academy', 'MHG Preparatory Academy'),
  ('middlesboro', 'Middlesboro High School', 'Middlesboro'),
  ('model', 'Model High School', 'Model'),
  ('monroe-county', 'Monroe County High School', 'Monroe County'),
  ('montgomery-county', 'Montgomery County High School', 'Montgomery County'),
  ('moore', 'Moore High School', 'Moore'),
  ('morgan-county', 'Morgan County High School', 'Morgan County'),
  ('muhlenberg-county', 'Muhlenberg County High School', 'Muhlenberg County'),
  ('murray', 'Murray High School', 'Murray'),
  ('nelson-county', 'Nelson County High School', 'Nelson County'),
  ('newcomer-academy', 'Newcomer Academy', 'Newcomer Academy'),
  ('newport-central-catholic', 'Newport Central Catholic High School', 'Newport Central Catholic'),
  ('newport', 'Newport High School', 'Newport'),
  ('nicholas-county', 'Nicholas County High School', 'Nicholas County'),
  ('north-bullitt', 'North Bullitt High School', 'North Bullitt'),
  ('north-hardin', 'North Hardin High School', 'North Hardin'),
  ('north-laurel', 'North Laurel High School', 'North Laurel'),
  ('north-oldham', 'North Oldham High School', 'North Oldham'),
  ('notre-dame-academy', 'Notre Dame Academy', 'Notre Dame Academy'),
  ('ohio-county', 'Ohio County High School', 'Ohio County'),
  ('oldham-county', 'Oldham County High School', 'Oldham County'),
  ('oneida-baptist-institute', 'Oneida Baptist Institute High School', 'Oneida Baptist Institute'),
  ('owen-county', 'Owen County High School', 'Owen County'),
  ('owensboro-catholic', 'Owensboro Catholic High School', 'Owensboro Catholic'),
  ('owensboro', 'Owensboro High School', 'Owensboro'),
  ('owsley-county', 'Owsley County High School', 'Owsley County'),
  ('paducah-tilghman', 'Paducah Tilghman High School', 'Paducah Tilghman'),
  ('paintsville', 'Paintsville High School', 'Paintsville'),
  ('paris', 'Paris High School', 'Paris'),
  ('paul-laurence-dunbar', 'Paul Laurence Dunbar High School', 'Paul Laurence Dunbar'),
  ('pendleton-county', 'Pendleton County High School', 'Pendleton County'),
  ('perry-county-central', 'Perry County Central High School', 'Perry County Central'),
  ('phelps', 'Phelps High School', 'Phelps'),
  ('piarist', 'Piarist High School', 'Piarist'),
  ('pike-county-central', 'Pike County Central High School', 'Pike County Central'),
  ('pikeville', 'Pikeville High School', 'Pikeville'),
  ('pineville', 'Pineville High School', 'Pineville'),
  ('pleasure-ridge-park', 'Pleasure Ridge Park High School', 'Pleasure Ridge Park'),
  ('portland-christian', 'Portland Christian High School', 'Portland Christian'),
  ('powell-county', 'Powell County High School', 'Powell County'),
  ('presentation-academy', 'Presentation Academy', 'Presentation Academy'),
  ('prestonsburg', 'Prestonsburg High School', 'Prestonsburg'),
  ('pulaski-county', 'Pulaski County High School', 'Pulaski County'),
  ('raceland', 'Raceland High School', 'Raceland'),
  ('red-bird-christian', 'Red Bird Christian High School', 'Red Bird Christian'),
  ('riverside-christian', 'Riverside Christian High School', 'Riverside Christian'),
  ('robertson-county', 'Robertson County High School', 'Robertson County'),
  ('rockcastle-county', 'Rockcastle County High School', 'Rockcastle County'),
  ('rose-hill-christian', 'Rose Hill Christian School', 'Rose Hill Christian'),
  ('rowan-county', 'Rowan County Senior High School', 'Rowan County'),
  ('russell-county', 'Russell County High School', 'Russell County'),
  ('russell', 'Russell High School', 'Russell'),
  ('russellville', 'Russellville High School', 'Russellville'),
  ('sacred-heart-academy', 'Sacred Heart Academy', 'Sacred Heart Academy'),
  ('saint-xavier', 'Saint Xavier High School', 'Saint Xavier'),
  ('sayre', 'Sayre High School', 'Sayre'),
  ('scott-county', 'Scott County High School', 'Scott County'),
  ('scott', 'Scott High School', 'Scott'),
  ('seneca', 'Seneca High School', 'Seneca'),
  ('shawnee', 'Shawnee High School', 'Shawnee'),
  ('shelby-county', 'Shelby County High School', 'Shelby County'),
  ('shelby-valley', 'Shelby Valley High School', 'Shelby Valley'),
  ('simon-kenton', 'Simon Kenton High School', 'Simon Kenton'),
  ('somerset-christian', 'Somerset Christian School', 'Somerset Christian'),
  ('somerset', 'Somerset High School', 'Somerset'),
  ('south-laurel', 'South Laurel High School', 'South Laurel'),
  ('south-oldham', 'South Oldham High School', 'South Oldham'),
  ('south-warren', 'South Warren High School', 'South Warren'),
  ('southern', 'Southern High School', 'Southern'),
  ('southwestern', 'Southwestern High School', 'Southwestern'),
  ('spencer-county', 'Spencer County High School', 'Spencer County'),
  ('st-henry-district', 'St. Henry District High School', 'St. Henry District'),
  ('st-mary', 'St. Mary High School', 'St. Mary'),
  ('st-patrick', 'St. Patrick High School', 'St. Patrick'),
  ('tates-creek', 'Tates Creek High School', 'Tates Creek'),
  ('taylor-county', 'Taylor County High School', 'Taylor County'),
  ('thomas-nelson', 'Thomas Nelson High School', 'Thomas Nelson'),
  ('todd-county-central', 'Todd County Central High School', 'Todd County Central'),
  ('trigg-county', 'Trigg County High School', 'Trigg County'),
  ('trimble-county', 'Trimble County High School', 'Trimble County'),
  ('trinity-louisville', 'Trinity (Louisville) High School', 'Trinity (Louisville)'),
  ('trinity-whitesville', 'Trinity (Whitesville) High School', 'Trinity (Whitesville)'),
  ('trinity-christian-academy', 'Trinity Christian Academy', 'Trinity Christian Academy'),
  ('union-county', 'Union County High School', 'Union County'),
  ('university-heights', 'University Heights High School', 'University Heights'),
  ('valley', 'Valley High School', 'Valley'),
  ('villa-madonna-academy', 'Villa Madonna Academy', 'Villa Madonna Academy'),
  ('w-e-b-dubois', 'W.E.B. DuBois High School', 'W.E.B. DuBois'),
  ('waggener', 'Waggener High School', 'Waggener'),
  ('walden', 'Walden High School', 'Walden'),
  ('walton-verona', 'Walton-Verona High School', 'Walton-Verona'),
  ('warren-central', 'Warren Central High School', 'Warren Central'),
  ('warren-east', 'Warren East High School', 'Warren East'),
  ('washington-county', 'Washington County High School', 'Washington County'),
  ('wayne-county', 'Wayne County High School', 'Wayne County'),
  ('webster-county', 'Webster County High School', 'Webster County'),
  ('west-carter', 'West Carter High School', 'West Carter'),
  ('west-jessamine', 'West Jessamine High School', 'West Jessamine'),
  ('western', 'Western High School', 'Western'),
  ('western-hills', 'Western Hills High School', 'Western Hills'),
  ('whitefield-academy', 'Whitefield Academy', 'Whitefield Academy'),
  ('whitley-county', 'Whitley County High School', 'Whitley County'),
  ('williamsburg', 'Williamsburg High School', 'Williamsburg'),
  ('williamstown', 'Williamstown High School', 'Williamstown'),
  ('wolfe-county', 'Wolfe County High School', 'Wolfe County'),
  ('woodford-county', 'Woodford County High School', 'Woodford County')
) AS v(slug, name, short_name)
CROSS JOIN data_source ds
WHERE ds.slug = 'staff-entry'
ON CONFLICT (slug) DO UPDATE
  SET name = EXCLUDED.name,
      short_name = EXCLUDED.short_name,
      updated_at = now();
